### ISSUE TITLE
Make a short tutorial or a video on how to use the extension

### ISSUE THREAD

**Issue by rrrazor** [Madmous/vscode-makefile-command-runner#2]

**Comment by Madmous** [comment]
Will upload a bunch of videos on how to use this extension soon.

Thank for taking the time to submit this issue @rrrazor

**Comment by Madmous** [comment]
Hello @rrrazor could you check the recent readme changes and let me know what is missing. I'd like your feedback to improve the documentation.

Cheers

**Comment by rrrazor** [comment]
@Madmous, thank you! Now it's clearer how to use the extension!
